apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    url: 10.5.0.6:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: "postgres"
    jsonData:
      sslmode: "disable"
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 903
      timescaledb: false